### ISSUE TITLE
[colm] iterating and modifying a struct field does not leave field changed

### ISSUE THREAD

**Issue by adriandt** [adriandt/colm-suite#61]
The following modification does not work. From genf

<pre>
    Packet->PacketDef = PacketDef
                
    Offset: int = 0
    for FD: pkt_field_def in Packet->PacketDef {
        switch FD.pkt_field_type
        case [`bool] {
            FD.Offset = Offset
            Offset = Offset + 1
        }           
        case [`long] {
            FD.Offset = Offset
            Offset = Offset + 8
        }
        case [`string] {
            FD.Offset = Offset
            Offset = Offset + 4
        }   
        case [list_type] {
            FD.Offset = Offset
            Offset = Offset + 4
        }   
    }
</pre>

**Comment by ehdtee** [comment]
self-contained reproduction:
<pre>
struct structure
    GD: grammar_def
end

def grammar_def
    [level1]

def level1
    [level2]

def level2
    [id]

token id /[a-z]+/

global S: structure = new structure()

S->GD = cons grammar_def "id" 
   
for L: level1 in S->GD
{
    L.level2 = cons level2 "hi"
}   

print "[S->GD]
</pre>

**Comment by adriandt** [comment]
This is a bug only in the sense that the necessary instructions are not implemented. In actuality it should be unchanged because a reference of a non-referencable thing is made. What should be happening is the iterator made constant and the assignment prevented.

**Comment by adriandt** [comment]
Implemented missing instruction in 06fbe467c0b900ce20705ad3b4eb8e8454b4a56e and opened #99 to capture the need to set iterators constant.
