### ISSUE TITLE
[ragel] fbreak setting CS = 0 in eof actions in G2 code

### ISSUE THREAD

**Issue by adriandt** [adriandt/colm-suite#76]
In ragel 6 an fbreak in EOF actions will set CS = 0 in G2 code. Caused by the csForced parameter and passing the error state as the next state. This is clearly wrong.

In non-G2 code you get the correct results, which is to leave CS alone.

Not sure the state of this in ragel 7.

https://www.colm.net/pipermail/ragel-users/2019-November/003647.html

**Comment by dgryski** [comment]
Should we check for other variables that have different behaviours between backends?  (Both language backends and table vs goto-based matchers)?

**Comment by ehdtee** [comment]
If it is covered by a test case then it is okay. I don't think there others, but then again I missed fbreak in an eof action.

**Comment by ehdtee** [comment]
<pre>
diff --git a/ragel/goipgoto.cpp b/ragel/goipgoto.cpp
index 55d1891..359c986 100644
--- a/ragel/goipgoto.cpp
+++ b/ragel/goipgoto.cpp
@@ -324,7 +324,7 @@ std::ostream &GoIpGotoCodeGen::FINISH_CASES( int level )
 
                        /* Write each action in the eof action list. */
                        for ( GenActionTable::Iter item = act->key; item.lte(); item++ )
-                               ACTION( out, item->value, STATE_ERR_STATE, true, false );
+                               ACTION( out, item->value, STATE_ERR_STATE, true, true );
                }
        }
</pre>

**Comment by adriandt** [comment]
Verified not an issue in ragel 7.
